#+TITLE:My Nyxt Configuration Files

This is my repo with small tweaks to Nyxt that make it more
comfortable and personal. Things of interest here:

* Alternative format for status-buffer (=status.lisp=)

I don't like the default wordy version of status-buffer (especially
with long mode names), so I define my own =short-format-status= to make
modeline a bit more minimalistic. Several helper functions
(=format-short-status-*=) are there to make things easier. 

This can evolve into an extension someday.

* Lots of search engines for different things
I've just added several search engines to quickly search through
Internet when I need to. One plan I haven't yet implemented is to use
some reverse image search engine through Nyxt search engines system
and some [[http://www.lispworks.com/documentation/HyperSpec/Body/22_ced.htm][accidentally Turing-complete part of format]]. The obstacle is
that you can't set the file-picker HTML element's value via script --
it's only user that can do that.

* A =setup-keepassxc= helper-command (=passwd.lisp=)

This prompts you for the KeePassXC DB password until it's unlocked and
saves the password to the interface. The raison d'être for this
command is that you can't set the master-password for the database in
the publicly available configuration file. The best you can do (except
for closing the source of the configuration) is to have a one-shot
command that will Do What You Mean most of the time.
